/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as core from "./core";
export type { core };
import type * as extensions from "./extensions";
export type { extensions };
import type * as permissions from "./permissions";
export type { permissions };
export type { ERC1155Creator } from "./ERC1155Creator";
