/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AdminControl__factory } from "./AdminControl__factory";
export { IAdminControl__factory } from "./IAdminControl__factory";
