/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC1155CreatorExtensionApproveTransfer__factory } from "./IERC1155CreatorExtensionApproveTransfer__factory";
export { IERC1155CreatorExtensionBurnable__factory } from "./IERC1155CreatorExtensionBurnable__factory";
