/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1155CreatorExtensionApproveTransfer } from "./IERC1155CreatorExtensionApproveTransfer";
export type { IERC1155CreatorExtensionBurnable } from "./IERC1155CreatorExtensionBurnable";
