/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC1155CreatorMintPermissions,
  IERC1155CreatorMintPermissionsInterface,
} from "../../../../../../@manifoldxyz/creator-core-solidity/contracts/permissions/ERC1155/IERC1155CreatorMintPermissions";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "extension",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "to",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "tokenIds",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    name: "approveMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC1155CreatorMintPermissions__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1155CreatorMintPermissionsInterface {
    return new utils.Interface(_abi) as IERC1155CreatorMintPermissionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1155CreatorMintPermissions {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC1155CreatorMintPermissions;
  }
}
