/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICreatorExtensionTokenURI,
  ICreatorExtensionTokenURIInterface,
} from "../../../../../@manifoldxyz/creator-core-solidity/contracts/extensions/ICreatorExtensionTokenURI";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICreatorExtensionTokenURI__factory {
  static readonly abi = _abi;
  static createInterface(): ICreatorExtensionTokenURIInterface {
    return new utils.Interface(_abi) as ICreatorExtensionTokenURIInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICreatorExtensionTokenURI {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ICreatorExtensionTokenURI;
  }
}
